#!/usr/bin/env python3
"""Delivery-bundle manager for the idea-to-code skill.

Cross-platform: works anywhere Python 3.8+ is installed.
Invocation (bash on Windows/macOS/Linux):
    python <path-to-idea-to-code>/scripts/manage_delivery_bundle.py <command> ...

The bundle lives under <project-root>/.idea-to-code/<slug>/ and holds:
    00-idea.md, 01-requirements.md, 02-prd.md,
    03-milestones.md, 04-verification.md, 05-final-report.md,
    06-acceptance.md, status.json
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


SCHEMA_VERSION = 3

# Heading translations used by the `translate-report` helper.
# Only section headings are mapped — body prose is left verbatim for the
# caller to rewrite in the target language.
HEADING_TRANSLATIONS = {
    "en": {
        "Final Report": "Final Report",
        "Target": "Target",
        "Milestones": "Milestones",
        "Implementation": "Implementation",
        "Verification": "Verification",
        "Visual Evidence": "Visual Evidence",
        "Risks And Follow-Up": "Risks and Follow-Up",
        "Trace Matrix": "Trace Matrix",
    },
    "zh": {
        "Final Report": "最终报告",
        "Target": "目标",
        "Milestones": "里程碑",
        "Implementation": "实现",
        "Verification": "验证",
        "Visual Evidence": "视觉证据",
        "Risks And Follow-Up": "风险与后续工作",
        "Trace Matrix": "追溯矩阵",
    },
    "ja": {
        "Final Report": "最終レポート",
        "Target": "目的",
        "Milestones": "マイルストーン",
        "Implementation": "実装",
        "Verification": "検証",
        "Visual Evidence": "ビジュアル証跡",
        "Risks And Follow-Up": "リスクとフォローアップ",
        "Trace Matrix": "トレースマトリクス",
    },
}
TRANSLATE_LANGS = tuple(HEADING_TRANSLATIONS)
REQUIREMENT_TYPES = ("functional", "nonfunctional", "constraint")

FILES = {
    "00-idea.md": (
        "# Idea\n\n"
        "- Title: {title}\n"
        "- Slug: {slug}\n"
        "- Created At (UTC): {created_at}\n\n"
        "## User Idea\n\n"
        "{idea_body}\n\n"
        "## Desired Outcome\n\n-\n"
    ),
    "01-requirements.md": (
        "# Requirements\n\n"
        "- Target outcome:\n"
        "- Primary user:\n"
        "- Main flow:\n"
        "- Success criteria:\n"
        "- Non-goals:\n"
        "- Constraints:\n"
        "- Unknowns:\n"
    ),
    "02-prd.md": (
        "# PRD\n\n"
        "## Goal\n\n-\n\n"
        "## Users\n\n-\n\n"
        "## Main Flows\n\n-\n\n"
        "## Scope\n\n- In scope:\n- Out of scope:\n\n"
        "## Functional Requirements\n\n-\n\n"
        "## Technical Shape\n\n-\n\n"
        "## Acceptance\n\n-\n"
    ),
    "03-milestones.md": (
        "# Milestones\n\n"
        "## Current Phase\n\n"
        "- Status: in_progress\n"
        "- Current focus:\n"
        "- Next gate:\n\n"
        "## Milestone History\n\n"
    ),
    "04-verification.md": (
        "# Verification\n\n"
        "## Coverage Expectations\n\n"
        "- Build:\n"
        "- Unit/Integration:\n"
        "- End-to-end flow:\n"
        "- Remaining gaps:\n\n"
        "## Verification History\n\n"
    ),
    "05-final-report.md": (
        "# Final Report\n\n"
        "_Generated by finalize. Edit before finalize or pass --force to overwrite._\n\n"
        "## Target\n\n-\n\n"
        "## Milestones\n\n-\n\n"
        "## Implementation\n\n-\n\n"
        "## Verification\n\n-\n\n"
        "## Visual Evidence\n\n-\n\n"
        "## Risks And Follow-Up\n\n-\n"
    ),
    "06-acceptance.md": (
        "# Acceptance\n\n"
        "- Requested scope delivered:\n"
        "- Verification gate:\n"
        "- Decision:\n"
        "- Acceptance notes:\n"
        "- Deferred work:\n"
    ),
}

EDITABLE_SECTIONS = {
    "idea": "00-idea.md",
    "requirements": "01-requirements.md",
    "prd": "02-prd.md",
    "verification": "04-verification.md",
}
# 03-milestones.md, 05-final-report.md, 06-acceptance.md are script-managed
# (checkpoint / finalize overwrite them); don't expose via update.

GATE_CHOICES = ("pass", "partial", "fail")
DECISION_CHOICES = ("accepted", "accepted-with-followup", "not-accepted")


# ---------- helpers ----------

def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def bundle_dir(root: Path, slug: str) -> Path:
    return root / ".idea-to-code" / slug


def ensure_bundle(root: Path, slug: str) -> Path:
    target = bundle_dir(root, slug)
    if not target.exists():
        raise SystemExit(
            f"Bundle does not exist: {target}\n"
            "Run 'init' first, or check --root / --slug."
        )
    return target


def render_template(content: str, **fields: str) -> str:
    defaults = {"idea_body": ""}
    defaults.update(fields)
    return content.format(**defaults)


def ensure_file(path: Path, content: str) -> None:
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def read_status(target: Path) -> dict:
    status_path = target / "status.json"
    status = json.loads(status_path.read_text(encoding="utf-8"))
    status.setdefault("schema_version", 1)
    status.setdefault("milestones", [])
    status.setdefault("blocks", [])
    status.setdefault("requirements", [])
    return status


def write_status(target: Path, status: dict) -> None:
    status["updated_at_utc"] = utc_now()
    (target / "status.json").write_text(
        json.dumps(status, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def rewrite_current_phase(milestones_path: Path, replacement_lines: list[str]) -> None:
    """Replace or insert the `## Current Phase` block inside 03-milestones.md.

    - Replaces the existing block if found.
    - Prepends the block (with a trailing blank line before any other content)
      if the header is missing. Previous version silently dropped it.
    """
    original = milestones_path.read_text(encoding="utf-8") if milestones_path.exists() else ""
    lines = original.splitlines()
    out: list[str] = []
    in_phase = False
    written = False
    for line in lines:
        if line.strip() == "## Current Phase":
            in_phase = True
            written = True
            out.extend(replacement_lines)
            continue
        if in_phase and line.startswith("## ") and line.strip() != "## Current Phase":
            in_phase = False
            out.append(line)
            continue
        if not in_phase:
            out.append(line)
    if not written:
        header_idx = 0
        for i, line in enumerate(out):
            if line.startswith("# "):
                header_idx = i + 1
                break
        prefix, suffix = out[:header_idx], out[header_idx:]
        if prefix and prefix[-1] != "":
            prefix.append("")
        out = prefix + replacement_lines + suffix
    # Keep a trailing blank line so subsequent `append` calls produce
    # a blank separator line before their own `## ` section header.
    milestones_path.write_text("\n".join(out).rstrip() + "\n\n", encoding="utf-8")


def current_phase_block(status: str, focus: str, next_gate: str) -> list[str]:
    return [
        "## Current Phase",
        "",
        f"- Status: {status}",
        f"- Current focus: {focus}",
        f"- Next gate: {next_gate}",
        "",
    ]


def is_template_unchanged(path: Path, default: str) -> bool:
    if not path.exists():
        return True
    return path.read_text(encoding="utf-8").strip() == default.strip()


def backup_if_edited(path: Path, default: str) -> Path | None:
    if path.exists() and not is_template_unchanged(path, default):
        backup = path.with_suffix(path.suffix + ".bak")
        shutil.copy2(path, backup)
        return backup
    return None


def read_content_arg(content: str | None, content_file: str | None) -> str:
    if content is not None and content_file is not None:
        raise SystemExit("Pass either --content or --content-file, not both.")
    if content_file is not None:
        return Path(content_file).read_text(encoding="utf-8")
    if content is None:
        raise SystemExit("Provide --content or --content-file.")
    return content


# ---------- subcommands ----------

def init_bundle(root: Path, slug: str, title: str, idea: str, unique: bool) -> Path:
    if unique:
        slug = f"{datetime.now().strftime('%Y%m%d-%H%M')}-{slug}"
    target = bundle_dir(root, slug)
    target.mkdir(parents=True, exist_ok=True)
    created_at = utc_now()
    for filename, template in FILES.items():
        ensure_file(
            target / filename,
            render_template(
                template,
                title=title,
                slug=slug,
                created_at=created_at,
                idea_body=idea or "-",
            ),
        )
    status_path = target / "status.json"
    if not status_path.exists():
        status = {
            "schema_version": SCHEMA_VERSION,
            "title": title,
            "slug": slug,
            "created_at_utc": created_at,
            "updated_at_utc": created_at,
            "state": "in_progress",
            "current_focus": "",
            "next_gate": "",
            "finalized_at_utc": None,
            "milestones": [],
            "blocks": [],
            "requirements": [],
            "gate_status": None,
            "decision": None,
        }
        write_status(target, status)
    return target


def _parse_ids(raw: str | None) -> list[str]:
    if not raw:
        return []
    return [x.strip() for x in raw.split(",") if x.strip()]


def checkpoint_bundle(
    root: Path,
    slug: str,
    milestone: str,
    delivered: str,
    verified: str,
    next_step: str,
    focus: str,
    gate: str,
    gate_status: str | None,
    covers: list[str],
) -> Path:
    target = ensure_bundle(root, slug)
    timestamp = utc_now()

    status = read_status(target)
    known_ids = {r["id"] for r in status.get("requirements", [])}
    unknown = [c for c in covers if c not in known_ids]
    if unknown and known_ids:
        raise SystemExit(
            "checkpoint --covers references unknown requirement IDs: "
            + ", ".join(unknown)
            + "\nAdd them first with 'requirement add' or drop them from --covers."
        )

    gate_suffix = f" (gate: {gate_status})" if gate_status else ""
    covers_line = f"- Covers: {', '.join(covers)}\n" if covers else ""
    (target / "03-milestones.md").open("a", encoding="utf-8").write(
        f"## {milestone}{gate_suffix}\n\n"
        f"- Timestamp: {timestamp}\n"
        f"- Delivered: {delivered}\n"
        f"- Verified: {verified}\n"
        f"- Next: {next_step}\n"
        f"{covers_line}"
        f"\n"
    )
    (target / "04-verification.md").open("a", encoding="utf-8").write(
        f"## {milestone}{gate_suffix}\n\n"
        f"- Timestamp: {timestamp}\n"
        f"- Verified: {verified}\n"
        f"{covers_line}"
        f"\n"
    )

    status["current_focus"] = focus
    status["next_gate"] = gate
    status["milestones"].append(
        {
            "name": milestone,
            "timestamp_utc": timestamp,
            "delivered": delivered,
            "verified": verified,
            "next": next_step,
            "gate_status": gate_status,
            "covers": covers,
        }
    )
    write_status(target, status)

    rewrite_current_phase(
        target / "03-milestones.md",
        current_phase_block("in_progress", focus, gate),
    )
    return target


def block_bundle(root: Path, slug: str, reason: str, need: str) -> Path:
    target = ensure_bundle(root, slug)
    timestamp = utc_now()
    status = read_status(target)
    status["state"] = "blocked"
    status["blocks"].append(
        {"timestamp_utc": timestamp, "reason": reason, "need": need}
    )
    write_status(target, status)

    (target / "03-milestones.md").open("a", encoding="utf-8").write(
        f"## Blocker at {timestamp}\n\n"
        f"- Reason: {reason}\n"
        f"- Needed to proceed: {need}\n\n"
    )
    rewrite_current_phase(
        target / "03-milestones.md",
        current_phase_block("blocked", f"BLOCKED: {reason}", f"unblock: {need}"),
    )
    return target


def unblock_bundle(root: Path, slug: str, note: str) -> Path:
    target = ensure_bundle(root, slug)
    timestamp = utc_now()
    status = read_status(target)
    status["state"] = "in_progress"
    if status["blocks"]:
        status["blocks"][-1]["resolved_at_utc"] = timestamp
        status["blocks"][-1]["resolution"] = note
    write_status(target, status)

    (target / "03-milestones.md").open("a", encoding="utf-8").write(
        f"## Unblocked at {timestamp}\n\n- Resolution: {note}\n\n"
    )
    rewrite_current_phase(
        target / "03-milestones.md",
        current_phase_block("in_progress", status.get("current_focus") or "", status.get("next_gate") or ""),
    )
    return target


def update_section(
    root: Path,
    slug: str,
    file_key: str,
    content: str,
    append: bool,
) -> Path:
    target = ensure_bundle(root, slug)
    filename = EDITABLE_SECTIONS[file_key]
    path = target / filename
    if append:
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        if existing and not existing.endswith("\n"):
            existing += "\n"
        path.write_text(existing + content.rstrip() + "\n", encoding="utf-8")
    else:
        path.write_text(content.rstrip() + "\n", encoding="utf-8")
    write_status(target, read_status(target))
    return path


def link_milestone(
    root: Path, slug: str, milestone: str, covers: list[str], replace: bool
) -> Path:
    target = ensure_bundle(root, slug)
    status = read_status(target)
    known = {r["id"] for r in status.get("requirements", [])}
    unknown = [c for c in covers if c not in known]
    if unknown:
        raise SystemExit(
            "link references unknown requirement IDs: "
            + ", ".join(unknown)
            + "\nAdd them first with 'requirement add'."
        )
    found = False
    for m in status["milestones"]:
        if m["name"] == milestone:
            found = True
            existing = set(m.get("covers") or [])
            new = set(covers)
            m["covers"] = sorted(new if replace else existing | new)
    if not found:
        raise SystemExit(f"Unknown milestone: {milestone}")
    write_status(target, status)
    return target


def requirement_add(
    root: Path, slug: str, rid: str, description: str, rtype: str
) -> Path:
    target = ensure_bundle(root, slug)
    status = read_status(target)
    if any(r["id"] == rid for r in status["requirements"]):
        raise SystemExit(f"Requirement already exists: {rid}")
    status["requirements"].append(
        {
            "id": rid,
            "description": description,
            "type": rtype,
            "created_at_utc": utc_now(),
            "state": "open",
        }
    )
    write_status(target, status)
    return target


def requirement_remove(root: Path, slug: str, rid: str) -> Path:
    target = ensure_bundle(root, slug)
    status = read_status(target)
    before = len(status["requirements"])
    status["requirements"] = [r for r in status["requirements"] if r["id"] != rid]
    if len(status["requirements"]) == before:
        raise SystemExit(f"Unknown requirement: {rid}")
    write_status(target, status)
    return target


def requirement_close(root: Path, slug: str, rid: str, note: str) -> Path:
    target = ensure_bundle(root, slug)
    status = read_status(target)
    for r in status["requirements"]:
        if r["id"] == rid:
            r["state"] = "closed"
            r["closed_at_utc"] = utc_now()
            r["closed_note"] = note
            write_status(target, status)
            return target
    raise SystemExit(f"Unknown requirement: {rid}")


def requirement_list(root: Path, slug: str) -> int:
    target = ensure_bundle(root, slug)
    status = read_status(target)
    coverage = _coverage_by_requirement(status)
    rows = []
    for r in status["requirements"]:
        covers = coverage.get(r["id"], [])
        rows.append({
            "id": r["id"],
            "type": r.get("type", "functional"),
            "state": r.get("state", "open"),
            "description": r["description"],
            "covered_by": [c["name"] for c in covers],
            "aggregate_gate": _aggregate_gate(covers),
        })
    print(json.dumps({"path": str(target), "requirements": rows}, indent=2, ensure_ascii=False))
    return 0


def _coverage_by_requirement(status: dict) -> dict[str, list[dict]]:
    coverage: dict[str, list[dict]] = {}
    for m in status.get("milestones", []):
        for rid in m.get("covers", []) or []:
            coverage.setdefault(rid, []).append(m)
    return coverage


def _aggregate_gate(covering_milestones: list[dict]) -> str:
    """Aggregate gate-status across the covering milestones.

    - any 'fail' -> fail
    - any 'partial' -> partial
    - all 'pass' -> pass
    - nothing covering -> 'uncovered'
    """
    if not covering_milestones:
        return "uncovered"
    statuses = {m.get("gate_status") for m in covering_milestones}
    if "fail" in statuses:
        return "fail"
    if "partial" in statuses or None in statuses:
        return "partial"
    if statuses == {"pass"}:
        return "pass"
    return "partial"


def _render_trace_matrix(status: dict) -> str:
    requirements = status.get("requirements", [])
    if not requirements:
        return "- No explicit requirements were recorded. Use `requirement add` to start a trace matrix.\n"
    coverage = _coverage_by_requirement(status)
    lines = [
        "| ID | Type | State | Description | Covered By | Aggregate Gate |",
        "|----|------|-------|-------------|-----------|----------------|",
    ]
    for r in requirements:
        covers = coverage.get(r["id"], [])
        covered_names = ", ".join(m["name"] for m in covers) if covers else "_(uncovered)_"
        lines.append(
            f"| {r['id']} | {r.get('type', 'functional')} | {r.get('state', 'open')} | "
            f"{r['description']} | {covered_names} | {_aggregate_gate(covers)} |"
        )
    return "\n".join(lines) + "\n"


def _render_milestones_rollup(milestones: list[dict]) -> str:
    if not milestones:
        return "- No milestones were recorded.\n"
    lines: list[str] = []
    for i, m in enumerate(milestones, start=1):
        gate = f" (gate: {m['gate_status']})" if m.get("gate_status") else ""
        lines.append(f"{i}. **{m['name']}**{gate} — {m['timestamp_utc']}")
        lines.append(f"   - Delivered: {m.get('delivered', '')}")
        lines.append(f"   - Verified: {m.get('verified', '')}")
        lines.append(f"   - Next: {m.get('next', '')}")
    return "\n".join(lines) + "\n"


def _finalize_integrity_problems(
    status: dict, gate_status: str, decision: str
) -> list[str]:
    """Cross-check claimed outcome against the bundle's actual trace matrix and blockers.

    Returns a list of human-readable problems. Empty list = claim is consistent.
    """
    problems: list[str] = []
    coverage = _coverage_by_requirement(status)
    open_reqs = [r for r in status.get("requirements", []) if r.get("state") != "closed"]
    uncovered = [r["id"] for r in open_reqs if not coverage.get(r["id"])]
    failing = [
        r["id"] for r in open_reqs
        if coverage.get(r["id"]) and _aggregate_gate(coverage[r["id"]]) == "fail"
    ]
    partial = [
        r["id"] for r in open_reqs
        if coverage.get(r["id"]) and _aggregate_gate(coverage[r["id"]]) == "partial"
    ]
    open_blockers = [
        b for b in status.get("blocks", []) if "resolved_at_utc" not in b
    ]

    if gate_status == "pass" and (failing or uncovered):
        parts = []
        if failing:
            parts.append(f"failing aggregates: {', '.join(failing)}")
        if uncovered:
            parts.append(f"uncovered requirements: {', '.join(uncovered)}")
        problems.append(
            "--gate-status pass conflicts with trace matrix (" + "; ".join(parts) + ")"
        )
    if gate_status == "pass" and partial:
        problems.append(
            "--gate-status pass conflicts with partial aggregates: "
            + ", ".join(partial)
        )

    if decision == "accepted":
        if uncovered:
            problems.append(
                "--decision accepted with uncovered requirements: "
                + ", ".join(uncovered)
            )
        if failing:
            problems.append(
                "--decision accepted with failing aggregates: "
                + ", ".join(failing)
            )
        if open_blockers:
            problems.append(
                f"--decision accepted with {len(open_blockers)} unresolved blocker(s)"
            )
    return problems


def finalize_bundle(
    root: Path,
    slug: str,
    summary: str,
    verification: str,
    risks: str,
    acceptance: str,
    gate_status: str,
    decision: str,
    acceptance_notes: str,
    deferred: str,
    force: bool,
) -> Path:
    target = ensure_bundle(root, slug)
    timestamp = utc_now()
    status = read_status(target)

    integrity_problems = _finalize_integrity_problems(status, gate_status, decision)
    if integrity_problems and not force:
        raise SystemExit(
            "finalize refused — the claim contradicts the bundle state:\n  - "
            + "\n  - ".join(integrity_problems)
            + "\nFix the milestones / requirements / blockers, lower --gate-status "
            "or --decision to match reality, or pass --force to override (the "
            "override is recorded in the final report)."
        )

    status["state"] = "completed" if decision == "accepted" else "closed"
    status["finalized_at_utc"] = timestamp
    status["gate_status"] = gate_status
    status["decision"] = decision
    if force and integrity_problems:
        status.setdefault("force_overrides", []).append(
            {
                "timestamp_utc": timestamp,
                "problems": integrity_problems,
                "gate_status": gate_status,
                "decision": decision,
            }
        )
    write_status(target, status)

    default_final = render_template(FILES["05-final-report.md"])
    default_accept = render_template(FILES["06-acceptance.md"])

    final_path = target / "05-final-report.md"
    accept_path = target / "06-acceptance.md"

    if not force:
        final_backup = backup_if_edited(final_path, default_final)
        accept_backup = backup_if_edited(accept_path, default_accept)
        if final_backup or accept_backup:
            msgs = []
            if final_backup:
                msgs.append(f"  05-final-report.md -> {final_backup.name}")
            if accept_backup:
                msgs.append(f"  06-acceptance.md -> {accept_backup.name}")
            print(
                "Backed up edited files before overwriting:\n" + "\n".join(msgs),
                file=sys.stderr,
            )

    milestone_rollup = _render_milestones_rollup(status["milestones"])
    matrix_block = _render_trace_matrix(status)
    block_summary = ""
    if status.get("blocks"):
        unresolved = [b for b in status["blocks"] if "resolved_at_utc" not in b]
        block_summary = f"- Total blockers encountered: {len(status['blocks'])} (unresolved: {len(unresolved)})\n"

    override_block = ""
    if force and integrity_problems:
        override_block = (
            "\n## Force Overrides\n\n"
            "The following integrity checks were bypassed via --force at finalize time:\n\n"
            + "".join(f"- {p}\n" for p in integrity_problems)
        )

    final_path.write_text(
        "# Final Report\n\n"
        f"## Target\n\n- {status['title']}\n\n"
        f"## Trace Matrix\n\n{matrix_block}\n"
        f"## Milestones\n\n{milestone_rollup}\n"
        f"## Implementation\n\n- {summary}\n\n"
        f"## Verification\n\n- Gate status: {gate_status}\n- {verification}\n{block_summary}\n"
        "## Visual Evidence\n\n- Attach screenshots or saved artifacts here when the task has UI or runtime output.\n\n"
        f"## Risks And Follow-Up\n\n- {risks}\n"
        f"{override_block}",
        encoding="utf-8",
    )

    accept_path.write_text(
        "# Acceptance\n\n"
        f"- Requested scope delivered: {acceptance}\n"
        f"- Verification gate: {gate_status}\n"
        f"- Decision: {decision}\n"
        f"- Acceptance notes: {acceptance_notes or '-'}\n"
        f"- Deferred work: {deferred or '-'}\n",
        encoding="utf-8",
    )

    rewrite_current_phase(
        target / "03-milestones.md",
        [
            "## Current Phase",
            "",
            f"- Status: {status['state']}",
            "- Current focus: final report delivered",
            f"- Gate status: {gate_status}",
            f"- Decision: {decision}",
            "",
        ],
    )
    return target


def print_status(root: Path, slug: str, full: bool) -> int:
    target = ensure_bundle(root, slug)
    status = read_status(target)
    summary = {
        "title": status["title"],
        "slug": status["slug"],
        "state": status.get("state", "in_progress"),
        "current_focus": status.get("current_focus", ""),
        "next_gate": status.get("next_gate", ""),
        "milestone_count": len(status.get("milestones", [])),
        "open_blockers": len(
            [b for b in status.get("blocks", []) if "resolved_at_utc" not in b]
        ),
        "gate_status": status.get("gate_status"),
        "decision": status.get("decision"),
        "updated_at_utc": status["updated_at_utc"],
        "path": str(target),
    }
    if full:
        summary["milestones"] = status.get("milestones", [])
        summary["blocks"] = status.get("blocks", [])
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


def verify_bundle(root: Path, slug: str) -> int:
    """Structural sanity check. Exits non-zero when required pieces are missing."""
    target = ensure_bundle(root, slug)
    problems: list[str] = []
    for name in FILES:
        p = target / name
        if not p.exists():
            problems.append(f"missing: {name}")
    if not (target / "status.json").exists():
        problems.append("missing: status.json")

    status = read_status(target) if (target / "status.json").exists() else {}
    if not status.get("milestones"):
        problems.append("status.json: no milestones recorded")
    idea_text = (target / "00-idea.md").read_text(encoding="utf-8") if (target / "00-idea.md").exists() else ""
    if "{idea_body}" in idea_text or idea_text.strip().endswith("## Desired Outcome\n\n-"):
        problems.append(
            "00-idea.md: still on template. Fix with: "
            f"update --root <root> --slug {slug} --file idea --content-file <path>"
        )

    # Trace matrix coverage: every open requirement must be covered by at least
    # one milestone. Fail-gated milestones count as coverage only in the sense
    # that the work was attempted; verify still flags them.
    coverage = _coverage_by_requirement(status)
    uncovered: list[str] = []
    failing: list[str] = []
    for r in status.get("requirements", []):
        if r.get("state") == "closed":
            continue
        covers = coverage.get(r["id"], [])
        if not covers:
            uncovered.append(r["id"])
        elif _aggregate_gate(covers) == "fail":
            failing.append(r["id"])
    if uncovered:
        problems.append(
            "trace matrix: uncovered requirements -> "
            + ", ".join(uncovered)
            + ". Fix by adding --covers to the relevant checkpoint, "
            + "running 'link --milestone <name> --covers <ids>' to attach an existing milestone, "
            + "or 'requirement close --id <id>' if the requirement was dropped."
        )
    if failing:
        problems.append(
            "trace matrix: covered but failing verification -> "
            + ", ".join(failing)
            + ". Run another milestone with gate-status pass/partial to improve the aggregate."
        )

    result = {
        "path": str(target),
        "ok": not problems,
        "problems": problems,
        "requirement_count": len(status.get("requirements", [])),
        "coverage": {
            rid: [m["name"] for m in covers]
            for rid, covers in coverage.items()
        },
    }
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0 if not problems else 1


def rebuild_markdown(root: Path, slug: str) -> Path:
    """Regenerate 03-milestones.md from status.json.

    Fixes formatting drift in old bundles (missing blank lines between entries,
    manual edits that dropped sections, etc.). Non-destructive: creates a .bak
    of the old file and rewrites from the authoritative status.json data.
    """
    target = ensure_bundle(root, slug)
    status = read_status(target)
    milestones_path = target / "03-milestones.md"
    if milestones_path.exists():
        backup = milestones_path.with_suffix(milestones_path.suffix + ".bak")
        shutil.copy2(milestones_path, backup)

    lines: list[str] = ["# Milestones", ""]

    state = status.get("state", "in_progress")
    focus = status.get("current_focus") or ""
    next_gate = status.get("next_gate") or ""
    current_block = ["## Current Phase", "", f"- Status: {state}"]
    if state == "completed" or state == "closed":
        gate_status = status.get("gate_status")
        decision = status.get("decision")
        current_block.append("- Current focus: final report delivered")
        if gate_status:
            current_block.append(f"- Gate status: {gate_status}")
        if decision:
            current_block.append(f"- Decision: {decision}")
    elif state == "blocked":
        latest_block = None
        for blk in status.get("blocks", []):
            if "resolved_at_utc" not in blk:
                latest_block = blk
                break
        reason = latest_block["reason"] if latest_block else ""
        need = latest_block["need"] if latest_block else ""
        current_block.append(f"- Current focus: BLOCKED: {reason}")
        current_block.append(f"- Next gate: unblock: {need}")
    else:
        current_block.append(f"- Current focus: {focus}")
        current_block.append(f"- Next gate: {next_gate}")
    current_block.append("")
    lines.extend(current_block)

    lines.append("## Milestone History")
    lines.append("")

    events: list[tuple[str, dict]] = []
    for m in status.get("milestones", []):
        events.append(("milestone", m))
    for blk in status.get("blocks", []):
        events.append(("block", blk))
    events.sort(key=lambda pair: pair[1].get("timestamp_utc", ""))

    for kind, entry in events:
        ts = entry.get("timestamp_utc", "")
        if kind == "milestone":
            gate_suffix = f" (gate: {entry['gate_status']})" if entry.get("gate_status") else ""
            lines.append(f"## {entry['name']}{gate_suffix}")
            lines.append("")
            lines.append(f"- Timestamp: {ts}")
            lines.append(f"- Delivered: {entry.get('delivered', '')}")
            lines.append(f"- Verified: {entry.get('verified', '')}")
            lines.append(f"- Next: {entry.get('next', '')}")
            if entry.get("covers"):
                lines.append(f"- Covers: {', '.join(entry['covers'])}")
            lines.append("")
        else:
            lines.append(f"## Blocker at {ts}")
            lines.append("")
            lines.append(f"- Reason: {entry.get('reason', '')}")
            lines.append(f"- Needed to proceed: {entry.get('need', '')}")
            if "resolved_at_utc" in entry:
                lines.append(f"- Resolved at: {entry['resolved_at_utc']}")
                lines.append(f"- Resolution: {entry.get('resolution', '')}")
            lines.append("")

    milestones_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    # 04-verification.md is the sibling history file; rebuild it too so the
    # two files don't drift apart after format fixes.
    verification_path = target / "04-verification.md"
    if verification_path.exists():
        v_backup = verification_path.with_suffix(verification_path.suffix + ".bak")
        shutil.copy2(verification_path, v_backup)

    v_lines: list[str] = [
        "# Verification",
        "",
        "## Coverage Expectations",
        "",
        "- Build:",
        "- Unit/Integration:",
        "- End-to-end flow:",
        "- Remaining gaps:",
        "",
        "## Verification History",
        "",
    ]
    for m in status.get("milestones", []):
        gate_suffix = f" (gate: {m['gate_status']})" if m.get("gate_status") else ""
        v_lines.append(f"## {m['name']}{gate_suffix}")
        v_lines.append("")
        v_lines.append(f"- Timestamp: {m.get('timestamp_utc', '')}")
        v_lines.append(f"- Verified: {m.get('verified', '')}")
        if m.get("covers"):
            v_lines.append(f"- Covers: {', '.join(m['covers'])}")
        v_lines.append("")
    verification_path.write_text("\n".join(v_lines).rstrip() + "\n", encoding="utf-8")

    return milestones_path


def translate_report(
    root: Path, slug: str, source: str, lang: str, target_name: str | None
) -> Path:
    target = ensure_bundle(root, slug)
    src = target / source
    if not src.exists():
        raise SystemExit(f"Source file does not exist: {src}")
    mapping = HEADING_TRANSLATIONS[lang]
    dst_name = target_name or src.stem + f".{lang}" + src.suffix
    dst = target / dst_name

    translated: list[str] = []
    for line in src.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        replaced = False
        for level in ("#", "##", "###"):
            prefix = f"{level} "
            if stripped.startswith(prefix):
                heading = stripped[len(prefix):].strip()
                if heading in mapping:
                    translated.append(f"{prefix}{mapping[heading]}")
                    replaced = True
                    break
        if not replaced:
            translated.append(line)

    banner = (
        f"<!-- translate-report: headings translated to '{lang}'. "
        "Body prose is left in the source language — translate inline with Edit. -->\n\n"
    )
    dst.write_text(banner + "\n".join(translated).rstrip() + "\n", encoding="utf-8")
    return dst


# ---------- CLI ----------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage idea-to-code delivery artifacts.")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("init", help="Create the delivery bundle.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--title", required=True)
    p.add_argument("--idea", default="", help="Seed text for 00-idea.md User Idea section.")
    p.add_argument("--unique", action="store_true", help="Prefix slug with YYYYMMDD-HHMM to avoid collisions.")

    p = sub.add_parser("checkpoint", help="Record a milestone.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--milestone", required=True)
    p.add_argument("--delivered", required=True)
    p.add_argument("--verified", required=True)
    p.add_argument("--next", dest="next_step", required=True)
    p.add_argument("--focus", required=True)
    p.add_argument("--gate", required=True, help="Human-readable next gate description.")
    p.add_argument("--gate-status", required=True, choices=GATE_CHOICES,
                   help="Verification outcome for this milestone: pass / partial / fail. Required — be honest; 'pass' with no evidence is how bundles get corrupted.")
    p.add_argument("--covers", default="",
                   help="Comma-separated requirement IDs this milestone delivers against.")

    p = sub.add_parser("requirement", help="Manage the trace matrix (requirement IDs and coverage).")
    req_sub = p.add_subparsers(dest="requirement_command", required=True)
    ra = req_sub.add_parser("add", help="Register a new requirement.")
    ra.add_argument("--root", required=True)
    ra.add_argument("--slug", required=True)
    ra.add_argument("--id", dest="rid", required=True)
    ra.add_argument("--description", required=True)
    ra.add_argument("--type", dest="rtype", default="functional", choices=REQUIREMENT_TYPES)
    rr = req_sub.add_parser("remove", help="Delete a requirement.")
    rr.add_argument("--root", required=True)
    rr.add_argument("--slug", required=True)
    rr.add_argument("--id", dest="rid", required=True)
    rc = req_sub.add_parser("close", help="Mark a requirement closed with a note.")
    rc.add_argument("--root", required=True)
    rc.add_argument("--slug", required=True)
    rc.add_argument("--id", dest="rid", required=True)
    rc.add_argument("--note", default="")
    rl = req_sub.add_parser("list", help="List requirements with coverage and aggregate gate status.")
    rl.add_argument("--root", required=True)
    rl.add_argument("--slug", required=True)

    p = sub.add_parser("link",
                       help="Retroactively attach requirement IDs to an already-recorded milestone.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--milestone", required=True, help="Exact milestone name as recorded.")
    p.add_argument("--covers", required=True, help="Comma-separated requirement IDs.")
    p.add_argument("--replace", action="store_true",
                   help="Replace existing covers instead of merging.")

    p = sub.add_parser("rebuild-markdown",
                       help="Regenerate 03-milestones.md from status.json (fixes historical formatting drift).")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)

    p = sub.add_parser("translate-report",
                       help="Clone a markdown file into a sibling with headings translated to another language.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--source", default="05-final-report.md",
                   help="Filename inside the bundle dir (default: 05-final-report.md).")
    p.add_argument("--lang", required=True, choices=TRANSLATE_LANGS)
    p.add_argument("--target", default=None,
                   help="Optional output filename (default: <stem>.<lang>.<ext>).")

    p = sub.add_parser("block", help="Mark bundle blocked on an external dependency.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--reason", required=True)
    p.add_argument("--need", required=True, help="What decision or dependency is needed to resume.")

    p = sub.add_parser("unblock", help="Clear the blocked state.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--note", required=True)

    p = sub.add_parser("update", help="Replace or append to 00/01/02 docs.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--file", required=True, choices=sorted(EDITABLE_SECTIONS))
    p.add_argument("--content", default=None)
    p.add_argument("--content-file", default=None)
    p.add_argument("--append", action="store_true", help="Append instead of replacing the file.")

    p = sub.add_parser("finalize", help="Close the bundle and emit the final report.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--summary", required=True)
    p.add_argument("--verification", required=True)
    p.add_argument("--risks", required=True)
    p.add_argument("--acceptance", required=True)
    p.add_argument("--gate-status", required=True, choices=GATE_CHOICES)
    p.add_argument("--decision", required=True, choices=DECISION_CHOICES)
    p.add_argument("--acceptance-notes", default="")
    p.add_argument("--deferred", default="")
    p.add_argument("--force", action="store_true",
                   help="Overwrite 05-final-report.md / 06-acceptance.md without creating .bak backups.")

    p = sub.add_parser("status", help="Print bundle status as JSON.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)
    p.add_argument("--full", action="store_true", help="Include milestone and blocker history.")

    p = sub.add_parser("verify", help="Check that the bundle is structurally complete.")
    p.add_argument("--root", required=True)
    p.add_argument("--slug", required=True)

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = Path(args.root).resolve()

    if args.command == "init":
        target = init_bundle(root, args.slug, args.title, args.idea, args.unique)
        print(target)
        return 0

    if args.command == "checkpoint":
        target = checkpoint_bundle(
            root, args.slug, args.milestone, args.delivered, args.verified,
            args.next_step, args.focus, args.gate, args.gate_status,
            _parse_ids(args.covers),
        )
        print(target)
        return 0

    if args.command == "requirement":
        if args.requirement_command == "add":
            print(requirement_add(root, args.slug, args.rid, args.description, args.rtype))
            return 0
        if args.requirement_command == "remove":
            print(requirement_remove(root, args.slug, args.rid))
            return 0
        if args.requirement_command == "close":
            print(requirement_close(root, args.slug, args.rid, args.note))
            return 0
        if args.requirement_command == "list":
            return requirement_list(root, args.slug)

    if args.command == "link":
        print(link_milestone(root, args.slug, args.milestone, _parse_ids(args.covers), args.replace))
        return 0

    if args.command == "rebuild-markdown":
        print(rebuild_markdown(root, args.slug))
        return 0

    if args.command == "translate-report":
        print(translate_report(root, args.slug, args.source, args.lang, args.target))
        return 0

    if args.command == "block":
        print(block_bundle(root, args.slug, args.reason, args.need))
        return 0

    if args.command == "unblock":
        print(unblock_bundle(root, args.slug, args.note))
        return 0

    if args.command == "update":
        content = read_content_arg(args.content, args.content_file)
        path = update_section(root, args.slug, args.file, content, args.append)
        print(path)
        return 0

    if args.command == "finalize":
        target = finalize_bundle(
            root, args.slug, args.summary, args.verification, args.risks,
            args.acceptance, args.gate_status, args.decision,
            args.acceptance_notes, args.deferred, args.force,
        )
        print(target)
        return 0

    if args.command == "status":
        return print_status(root, args.slug, args.full)

    if args.command == "verify":
        return verify_bundle(root, args.slug)

    raise SystemExit(f"Unknown command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
